"""Initial migration

Revision ID: cffc3827488b
Revises: 
Create Date: 2026-03-19 18:46:27.336278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cffc3827488b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plans', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('plans', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.drop_constraint(op.f('plans_ibfk_1'), 'plans', type_='foreignkey')
    op.drop_column('plans', 'plan_id')
    op.drop_index(op.f('uq_users_cpf'), table_name='users')
    op.drop_column('users', 'cpf')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('cpf', mysql.VARCHAR(length=11), nullable=True))
    op.create_index(op.f('uq_users_cpf'), 'users', ['cpf'], unique=True)
    op.add_column('plans', sa.Column('plan_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('plans_ibfk_1'), 'plans', 'plans', ['plan_id'], ['id'])
    op.alter_column('plans', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('plans', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
